import time

print("Ohhh....")
time.sleep(1)
print("Where am I?")
time.sleep(1)
print("I remember I was having my first space trip...")
time.sleep(1)
print("Ouch, my spaceship has crashed!")
time.sleep(1)
print("Calm down. I should check it at first.")
time.sleep(3)
print("It is damaged badly. But I can fix it.")
time.sleep(1)
print("As long as I find my chuchumexion and warp coil, which have been lost.")
time.sleep(1)
print("I have to find them back!")
time.sleep(1)
print("(You have to type 'load spacegame' to start the game settings.)")
